-- =========================================================
-- OPTIONAL: DROP TABLES
-- Run manually one by one if tables already exist
-- Ignore error if table does not exist
-- =========================================================

#CREATE DATABASE PHARMA_DB;
USE PHARMA_DB;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS FOCUSES_ON;
DROP TABLE IF EXISTS CONDUCTED_BY;
DROP TABLE IF EXISTS STUDIES;
DROP TABLE IF EXISTS IS_MARKETED_AS;
DROP TABLE IF EXISTS TREATS;
DROP TABLE IF EXISTS DRUG_INTERACTION;
DROP TABLE IF EXISTS DRUG_SIDE_EFFECT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CLINICAL_TRIAL;
DROP TABLE IF EXISTS RESEARCHER;
DROP TABLE IF EXISTS SIDE_EFFECTS;
DROP TABLE IF EXISTS DISEASE;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS DRUG;

SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- MAIN ENTITY TABLES
-- =========================================================

CREATE TABLE DRUG (
    DRUG_NAME        VARCHAR(255) PRIMARY KEY,
    DRUG_CATEGORY    VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DISEASE (
    DISEASE_NAME      VARCHAR(255) PRIMARY KEY,
    DISEASE_CATEGORY  VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SIDE_EFFECTS (
    SIDE_EFFECT_NAME  VARCHAR(255) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RESEARCHER (
    MAIN_RESEARCHER   VARCHAR(255) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMPANY (
    COMPANY_NAME      VARCHAR(255) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CLINICAL_TRIAL (
    CLINICAL_TRIAL_TITLE            VARCHAR(500) PRIMARY KEY,
    CLINICAL_TRIAL_START_DATE       DATE,
    CLINICAL_TRIAL_COMPLETION_DATE  DATE,
    CLINICAL_TRIAL_PARTICIPANTS     INT,
    CLINICAL_TRIAL_STATUS           VARCHAR(100),
    CLINICAL_TRIAL_ADDRESS          VARCHAR(255),
    CLINICAL_TRIAL_INSTITUTION      VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUCT (
    PRODUCT_NAME    VARCHAR(255) PRIMARY KEY,
    COMPANY_NAME    VARCHAR(255),
    CONSTRAINT FK_PRODUCT_COMPANY
        FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================================================
-- RELATIONSHIP TABLES
-- =========================================================

CREATE TABLE DRUG_SIDE_EFFECT (
    DRUG_NAME         VARCHAR(255),
    SIDE_EFFECT_NAME  VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, SIDE_EFFECT_NAME),
    CONSTRAINT FK_DSE_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DSE_SIDE_EFFECT FOREIGN KEY (SIDE_EFFECT_NAME)
        REFERENCES SIDE_EFFECTS(SIDE_EFFECT_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DRUG_INTERACTION (
    DRUG_NAME                 VARCHAR(255),
    INTERACTS_WITH_DRUG_NAME  VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, INTERACTS_WITH_DRUG_NAME),
    CONSTRAINT FK_DI_DRUG1 FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DI_DRUG2 FOREIGN KEY (INTERACTS_WITH_DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TREATS (
    DRUG_NAME      VARCHAR(255),
    DISEASE_NAME   VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, DISEASE_NAME),
    CONSTRAINT FK_TREATS_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TREATS_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IS_MARKETED_AS (
    DRUG_NAME      VARCHAR(255),
    PRODUCT_NAME   VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, PRODUCT_NAME),
    CONSTRAINT FK_IMA_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_IMA_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT(PRODUCT_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE STUDIES (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    DRUG_NAME             VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, DRUG_NAME),
    CONSTRAINT FK_STUDIES_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_STUDIES_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FOCUSES_ON (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    DISEASE_NAME          VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, DISEASE_NAME),
    CONSTRAINT FK_FO_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_FO_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CONDUCTED_BY (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    MAIN_RESEARCHER       VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, MAIN_RESEARCHER),
    CONSTRAINT FK_CB_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CB_RESEARCHER FOREIGN KEY (MAIN_RESEARCHER)
        REFERENCES RESEARCHER(MAIN_RESEARCHER)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;