-- DATABASE SETUP

-- Incase we need to drop tables why don't we just drop the entire db :)?
DROP DATABASE IF EXISTS PHARMA_DB;

CREATE DATABASE IF NOT EXISTS PHARMA_DB;
USE PHARMA_DB;

-- MAIN ENTITY TABLES

CREATE TABLE IF NOT EXISTS DRUG (
    DRUG_NAME        VARCHAR(255) PRIMARY KEY,
    DRUG_CATEGORY    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DISEASE (
    DISEASE_NAME      VARCHAR(255) PRIMARY KEY,
    DISEASE_CATEGORY  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SIDE_EFFECTS (
    SIDE_EFFECT_NAME  VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS RESEARCHER (
    MAIN_RESEARCHER   VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_NAME      VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CLINICAL_TRIAL (
    CLINICAL_TRIAL_TITLE            VARCHAR(500) PRIMARY KEY,
    CLINICAL_TRIAL_START_DATE       DATE,
    CLINICAL_TRIAL_COMPLETION_DATE  DATE,
    CLINICAL_TRIAL_PARTICIPANTS     INT,
    CLINICAL_TRIAL_STATUS           VARCHAR(100),
    CLINICAL_TRIAL_COUNTRY          VARCHAR(255),
    CLINICAL_TRIAL_DEPARTMENT       VARCHAR(255),
    CLINICAL_TRIAL_INSTITUTION      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_NAME    VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_NAME    VARCHAR(255) PRIMARY KEY
);

-- RELATIONSHIP TABLES

CREATE TABLE IF NOT EXISTS DRUG_SIDE_EFFECT (
    DRUG_NAME         VARCHAR(255),
    SIDE_EFFECT_NAME  VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, SIDE_EFFECT_NAME),
    CONSTRAINT FK_DSE_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DSE_SIDE_EFFECT FOREIGN KEY (SIDE_EFFECT_NAME)
        REFERENCES SIDE_EFFECTS(SIDE_EFFECT_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DRUG_INTERACTION (
    DRUG_NAME                 VARCHAR(255),
    INTERACTS_WITH_DRUG_NAME  VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, INTERACTS_WITH_DRUG_NAME),
    CONSTRAINT FK_DI_DRUG1 FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DI_DRUG2 FOREIGN KEY (INTERACTS_WITH_DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TREATS (
    DRUG_NAME      VARCHAR(255),
    DISEASE_NAME   VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, DISEASE_NAME),
    CONSTRAINT FK_TREATS_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TREATS_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IS_MARKETED_AS (
    DRUG_NAME      VARCHAR(255),
    PRODUCT_NAME   VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, PRODUCT_NAME),
    CONSTRAINT FK_IMA_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_IMA_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT(PRODUCT_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCED_BY (
    PRODUCT_NAME    VARCHAR(255),
    COMPANY_NAME    VARCHAR(255)
    PRIMARY KEY (PRODUCT_NAME, COMPANY_NAME)
    CONSTRAINT FK_IMA FOREIGN KEY (PRODUCT_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_IMA_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT(PRODUCT_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE IF NOT EXISTS STUDIES (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    DRUG_NAME             VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, DRUG_NAME),
    CONSTRAINT FK_STUDIES_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_STUDIES_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FOCUSES_ON (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    DISEASE_NAME          VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, DISEASE_NAME),
    CONSTRAINT FK_FO_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_FO_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CONDUCTED_BY (
    CLINICAL_TRIAL_TITLE  VARCHAR(500),
    MAIN_RESEARCHER       VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, MAIN_RESEARCHER),
    CONSTRAINT FK_CB_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CB_RESEARCHER FOREIGN KEY (MAIN_RESEARCHER)
        REFERENCES RESEARCHER(MAIN_RESEARCHER)
        ON DELETE CASCADE ON UPDATE CASCADE
);