-- =========================
-- DATABASE SETUP
-- =========================
DROP DATABASE IF EXISTS PHARMA_DB_TASK1;
CREATE DATABASE IF NOT EXISTS PHARMA_DB_TASK1;
USE PHARMA_DB_TASK1;

-- =========================
-- MAIN ENTITY TABLES
-- =========================

CREATE TABLE IF NOT EXISTS DRUG (
    DRUG_NAME       VARCHAR(255) PRIMARY KEY,
    DRUG_CATEGORY   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DISEASE (
    DISEASE_NAME       VARCHAR(255) PRIMARY KEY,
    DISEASE_CATEGORY   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SIDE_EFFECT (
    SIDE_EFFECT_NAME   VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS RESEARCHER (
    MAIN_RESEARCHER    VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS COMPANY (
    COMPANY_NAME       VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_NAME       VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CLINICAL_TRIAL (
    CLINICAL_TRIAL_TITLE             VARCHAR(500) PRIMARY KEY,
    CLINICAL_TRIAL_STATUS            VARCHAR(100),
    CLINICAL_TRIAL_COUNTRY           VARCHAR(255),
    CLINICAL_TRIAL_DEPARTMENT        VARCHAR(255),
    CLINICAL_TRIAL_INSTITUTION       VARCHAR(255),
    CLINICAL_TRIAL_START_DATE        DATE,
    CLINICAL_TRIAL_COMPLETION_DATE   DATE,
    CLINICAL_TRIAL_CONDITION         VARCHAR(255),
    CLINICAL_TRIAL_PARTICIPANTS      INT
);

-- =========================
-- RELATIONSHIP TABLES
-- =========================

-- STUDIES : CLINICAL_TRIAL (N) <-> (M) DRUG
CREATE TABLE IF NOT EXISTS STUDIES (
    CLINICAL_TRIAL_TITLE   VARCHAR(500),
    DRUG_NAME              VARCHAR(255),
    PRIMARY KEY (CLINICAL_TRIAL_TITLE, DRUG_NAME),
    CONSTRAINT FK_STUDIES_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_STUDIES_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- TREATS : DRUG (M) <-> (N) DISEASE
CREATE TABLE IF NOT EXISTS TREATS (
    DRUG_NAME        VARCHAR(255),
    DISEASE_NAME     VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, DISEASE_NAME),
    CONSTRAINT FK_TREATS_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_TREATS_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- HAS : DRUG (M) <-> (N) SIDE_EFFECT
CREATE TABLE IF NOT EXISTS HAS_SIDE_EFFECT (
    DRUG_NAME          VARCHAR(255),
    SIDE_EFFECT_NAME   VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, SIDE_EFFECT_NAME),
    CONSTRAINT FK_HAS_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_HAS_SIDE_EFFECT FOREIGN KEY (SIDE_EFFECT_NAME)
        REFERENCES SIDE_EFFECT(SIDE_EFFECT_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- INTERACTS_WITH : recursive M:N on DRUG
CREATE TABLE IF NOT EXISTS INTERACTS_WITH (
    DRUG_NAME                 VARCHAR(255),
    INTERACTS_WITH_DRUG_NAME  VARCHAR(255),
    PRIMARY KEY (DRUG_NAME, INTERACTS_WITH_DRUG_NAME),
    CONSTRAINT FK_INTERACTS_DRUG1 FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_INTERACTS_DRUG2 FOREIGN KEY (INTERACTS_WITH_DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CONDUCTED_BY : CLINICAL_TRIAL (1) <-> (1) RESEARCHER
-- Each trial has one main researcher
-- Each researcher is assigned to one trial in this ER version
CREATE TABLE IF NOT EXISTS CONDUCTED_BY (
    CLINICAL_TRIAL_TITLE   VARCHAR(500) PRIMARY KEY,
    MAIN_RESEARCHER        VARCHAR(255) UNIQUE,
    CONSTRAINT FK_CB_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CB_RESEARCHER FOREIGN KEY (MAIN_RESEARCHER)
        REFERENCES RESEARCHER(MAIN_RESEARCHER)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- FOCUSES_ON : CLINICAL_TRIAL (1) -> (N) DISEASE
-- One clinical trial focuses on one disease entry here
-- A disease can appear in many trials
CREATE TABLE IF NOT EXISTS FOCUSES_ON (
    CLINICAL_TRIAL_TITLE   VARCHAR(500) PRIMARY KEY,
    DISEASE_NAME           VARCHAR(255),
    CONSTRAINT FK_FO_TRIAL FOREIGN KEY (CLINICAL_TRIAL_TITLE)
        REFERENCES CLINICAL_TRIAL(CLINICAL_TRIAL_TITLE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_FO_DISEASE FOREIGN KEY (DISEASE_NAME)
        REFERENCES DISEASE(DISEASE_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- IS_MARKETED_AS : DRUG (1) -> (N) PRODUCT
-- One drug can have many products
-- Each product belongs to one drug
CREATE TABLE IF NOT EXISTS IS_MARKETED_AS (
    PRODUCT_NAME      VARCHAR(255) PRIMARY KEY,
    DRUG_NAME         VARCHAR(255),
    CONSTRAINT FK_IMA_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT(PRODUCT_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_IMA_DRUG FOREIGN KEY (DRUG_NAME)
        REFERENCES DRUG(DRUG_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- PRODUCED_BY : PRODUCT (N) -> (1) COMPANY
-- One company can produce many products
-- Each product is produced by one company
CREATE TABLE IF NOT EXISTS PRODUCED_BY (
    PRODUCT_NAME      VARCHAR(255) PRIMARY KEY,
    COMPANY_NAME      VARCHAR(255),
    CONSTRAINT FK_PB_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT(PRODUCT_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_PB_COMPANY FOREIGN KEY (COMPANY_NAME)
        REFERENCES COMPANY(COMPANY_NAME)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);