USE PHARMA_DB_TASK1;

SELECT DISTINCT d.DRUG_NAME, d.DRUG_CATEGORY
FROM DRUG d
JOIN TREATS t ON d.DRUG_NAME = t.DRUG_NAME
JOIN DISEASE dis ON t.DISEASE_NAME = dis.DISEASE_NAME
WHERE dis.DISEASE_CATEGORY = 'Endocrine';