USE PHARMA_DB_TASK1;

SELECT DRUG_NAME, COUNT(DISTINCT SIDE_EFFECT_NAME) AS SIDE_EFFECTS_COUNT
FROM HAS_SIDE_EFFECT
WHERE SIDE_EFFECT_NAME IN ('cough', 'headache')
GROUP BY DRUG_NAME
HAVING COUNT(DISTINCT SIDE_EFFECT_NAME) = 2;