USE PHARMA_DB_TASK1;

SELECT t.DRUG_NAME, COUNT(*) AS TREATMENT_COUNT
FROM TREATS t
JOIN DISEASE d ON t.DISEASE_NAME = d.DISEASE_NAME
WHERE d.DISEASE_CATEGORY = 'Immunological'
  AND t.DRUG_NAME NOT IN (
      SELECT DISTINCT t2.DRUG_NAME
      FROM TREATS t2
      JOIN DISEASE d2 ON t2.DISEASE_NAME = d2.DISEASE_NAME
      WHERE d2.DISEASE_CATEGORY = 'Hematological'
  )
GROUP BY t.DRUG_NAME
ORDER BY TREATMENT_COUNT DESC;