DROP TABLE INTERACTS_WITH CASCADE CONSTRAINTS;
DROP TABLE IS_MARKETED_AS CASCADE CONSTRAINTS;
DROP TABLE PRODUCED_BY CASCADE CONSTRAINTS;
DROP TABLE FOCUSES_ON CASCADE CONSTRAINTS;
DROP TABLE STUDIES CASCADE CONSTRAINTS;
DROP TABLE CONDUCTED_BY CASCADE CONSTRAINTS;
DROP TABLE TREATS CASCADE CONSTRAINTS;

DROP TABLE DRUG CASCADE CONSTRAINTS;
DROP TABLE SIDE_EFFECT CASCADE CONSTRAINTS;
DROP TABLE DISEASE CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE CLINICAL_TRIAL CASCADE CONSTRAINTS;
DROP TABLE RESEARCHER CASCADE CONSTRAINTS;

CREATE TABLE INTERACTS_WITH
CREATE TABLE IS_MARKETED_AS
CREATE TABLE PRODUCED_BY
CREATE TABLE FOCUSES_ON
CREATE TABLE STUDIES
CREATE TABLE CONDUCTED_BY
CREATE TABLE TREATS

CREATE TABLE DRUG(
    DRUG_NAME VARCHAR2(500) PRIMARY KEY,
    DRUG_CATEGORY VARCHAR2(500)
)
CREATE TABLE SIDE_EFFECT(
    SIDE_EFFECT_NAME VARCHAR2(500) PRIMARY KEY,
    SIDE_EFFECT_NOTE VARCHAR2(500)
)
CREATE TABLE DISEASE(
    DISEASE_NAME VARCHAR2(500) PRIMARY KEY,
    DISEASE_CATEGORY VARCHAR2(500)
)
CREATE TABLE PRODUCTS(
    PRODUCT_NAME VARCHAR2(500) PRIMARY KEY
)
CREATE TABLE COMPANY(
    COM
)
CREATE TABLE CLINICAL_TRIAL
CREATE TABLE RESEARCHER
