USE PHARMA_DB_TASK1;
SELECT DISTINCT DRUG_NAME
FROM INTERACTS_WITH
WHERE INTERACTS_WITH_DRUG_NAME = 'butabarbital'

UNION

SELECT DISTINCT INTERACTS_WITH_DRUG_NAME
FROM INTERACTS_WITH
WHERE DRUG_NAME = 'butabarbital';